name: CI
on: [push]
jobs:
  rspec:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        ruby: ['3.2', '3.0', '2.7', 'truffleruby-head']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle install
      run: bundle install --jobs 4 --retry 3
    - name: Run Rspec
      run: bundle exec rspec
